apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
  namespace: assessments-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
        - name: nextjs-app
          image: ghcr.io/karthi216/devops-nextjs-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000













