apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
  namespace: assessments-dev
spec:
  type: NodePort
  selector:
    app: nextjs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000




