apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
spec:
  type: NodePort
  selector:
    app: nextjs-app
  ports:
    - protocol: TCP
      port: 80          # accessible within the cluster
      targetPort: 3000  # inside the container
      nodePort: 30080   # accessible from outside via <node-ip>:30080



